[versions]
agp = "8.6.0"
kotlin = "1.8.10"
core-ktx = "1.10.1"
ksp = "1.8.10-1.0.9"
hidden-api-refine = "4.3.0"

zygoteLoader = "1.0.1"

[libraries]

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }

zygoteLoader = { module = "com.github.vova7878:ZygoteLoader", version.ref = "zygoteLoader" }

[plugins]

androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hiddenApiRefine = { id = "dev.rikka.tools.refine", version.ref = "hidden-api-refine" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
